# Generated by Django 4.2.4 on 2023-09-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='Rakha Fadil Atmojo', max_length=255)),
                ('npm', models.CharField(default='2206082985', max_length=255)),
                ('pbpclass', models.CharField(default='PBP C', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
