# Generated by Django 4.2.4 on 2023-09-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
