# Generated by Django 4.2.4 on 2023-09-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.TextField(default=' '),
        ),
    ]
