# Generated by Django 4.2.4 on 2023-09-18 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_item_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='item',
            name='npm',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pbpclass',
        ),
    ]
