# Generated by Django 4.2.4 on 2023-09-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_item_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='creator',
            field=models.CharField(max_length=255),
        ),
    ]
