# Generated by Django 4.2.4 on 2023-09-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_item_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='npm',
            field=models.BigIntegerField(default=2206082985),
        ),
        migrations.AddField(
            model_name='item',
            name='pbpclass',
            field=models.CharField(default='PBP C', max_length=255),
        ),
    ]
