# Generated by Django 4.2.4 on 2023-09-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_item_npm_item_pbpclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='npm',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='pbpclass',
            field=models.CharField(max_length=255),
        ),
    ]
