# Generated by Django 4.2.4 on 2023-09-16 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_delete_product'),
        ('main', '0013_alter_item_creator_alter_item_npm_and_more'),
    ]

    operations = [
    ]
